# Data Transformation

The idea of this file is to clean and merge the two dataset that we have fetched from the SWAPI

In [13]:
import pandas as pd

In [14]:
swapi_char = pd.read_csv(".\data\swapi_char.csv")
swapi_details = pd.read_csv(".\data\swapi_details.csv")
swapi_homeworld = pd.read_csv(".\data\swapi_homeworld.csv")

### Concat the two tables to be one table

In [15]:
df = pd.concat([swapi_char,swapi_details, swapi_homeworld], axis=1)

In [16]:
df

,uid,name,url,name,height,mass,hair_color,skin_color,eye_color,birth_year,...,homeworld,homeworld_name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population
0,1,Luke Skywalker,https://www.swapi.tech/api/people/1,Luke Skywalker,172,77,blond,fair,blue,19BBY,...,https://swapi.info/api/planets/1,Tatooine,23.0,304.0,10465.0,arid,1 standard,desert,1,200000
1,2,C-3PO,https://www.swapi.tech/api/people/2,C-3PO,167,75,NaN,gold,yellow,112BBY,...,https://swapi.info/api/planets/1,Tatooine,23.0,304.0,10465.0,arid,1 standard,desert,1,200000
2,3,R2-D2,https://www.swapi.tech/api/people/3,R2-D2,96,32,NaN,white,blue,red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Darth Vader,https://www.swapi.tech/api/people/4,Darth Vader,202,136,none,white,yellow,41.9BBY,...,https://swapi.info/api/planets/1,Tatooine,23.0,304.0,10465.0,arid,1 standard,desert,1,200000
4,5,Leia Organa,https://www.swapi.tech/api/people/5,Leia Organa,150,49,brown,light,brown,19BBY,...,https://swapi.info/api/planets/2,Alderaan,24.0,364.0,12500.0,temperate,1 standard,"grasslands, mountains",40,2000000000
5,6,Owen Lars,https://www.swapi.tech/api/people/6,Owen Lars,178,120,brown,grey,light,blue,...,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,Beru Whitesun lars,https://www.swapi.tech/api/people/7,Beru Whitesun lars,165,75,brown,light,blue,47BBY,...,https://swapi.info/api/planets/1,Tatooine,23.0,304.0,10465.0,arid,1 standard,desert,1,200000
7,8,R5-D4,https://www.swapi.tech/api/people/8,R5-D4,97,32,NaN,white,red,red,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,Biggs Darklighter,https://www.swapi.tech/api/people/9,Biggs Darklighter,183,84,black,light,brown,24BBY,...,https://swapi.info/api/planets/1,Tatooine,23.0,304.0,10465.0,arid,1 standard,desert,1,200000
9,10,Obi-Wan Kenobi,https://www.swapi.tech/api/people/10,Obi-Wan Kenobi,182,77,auburn,white,fair,blue-gray,...,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,Anakin Skywalker,https://www.swapi.tech/api/people/11,Anakin Skywalker,188,84,blond,fair,blue,41.9BBY,...,https://swapi.info/api/planets/1,Tatooine,23.0,304.0,10465.0,arid,1 standard,desert,1,200000
11,12,Wilhuff Tarkin,https://www.swapi.tech/api/people/12,Wilhuff Tarkin,180,unknown,auburn,grey,fair,blue,...,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,Chewbacca,https://www.swapi.tech/api/people/13,Chewbacca,228,112,brown,unknown,blue,200BBY,...,https://swapi.info/api/planets/14,Kashyyyk,26.0,381.0,12765.0,tropical,1 standard,"jungle, forests, lakes, rivers",60,45000000
13,14,Han Solo,https://www.swapi.tech/api/people/14,Han Solo,180,80,brown,fair,brown,29BBY,...,https://swapi.info/api/planets/22,Corellia,25.0,329.0,11000.0,temperate,1 standard,"plains, urban, hills, forests",70,3000000000
14,15,Greedo,https://www.swapi.tech/api/people/15,Greedo,173,74,NaN,green,black,44BBY,...,https://swapi.info/api/planets/23,Rodia,29.0,305.0,7549.0,hot,1 standard,"jungles, oceans, urban, swamps",60,1300000000
15,16,Jabba Desilijic Tiure,https://www.swapi.tech/api/people/16,Jabba Desilijic Tiure,175,1,358,NaN,green-tan,brown,...,600BBY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,18,Wedge Antilles,https://www.swapi.tech/api/people/18,Wedge Antilles,170,77,brown,fair,hazel,21BBY,...,https://swapi.info/api/planets/22,Corellia,25.0,329.0,11000.0,temperate,1 standard,"plains, urban, hills, forests",70,3000000000
17,19,Jek Tono Porkins,https://www.swapi.tech/api/people/19,Jek Tono Porkins,180,110,brown,fair,blue,unknown,...,https://swapi.info/api/planets/26,Bestine IV,26.0,680.0,6400.0,temperate,unknown,"rocky islands, oceans",98,62000000
18,20,Yoda,https://www.swapi.tech/api/people/20,Yoda,66,17,white,green,brown,896BBY,...,https://swapi.info/api/planets/28,unknown,0.0,0.0,0.0,unknown,unknown,unknown,unknown,unknown
19,21,Palpatine,https://www.swapi.tech/api/people/21,Palpatine,170,75,grey,pale,yellow,82BBY,...,https://swapi.info/api/planets/8,Naboo,26.0,312.0,12120.0,temperate,1 standard,"grassy hills, swamps, forests, mountains",12,4500000000
20,22,Boba Fett,https://www.swapi.tech/api/people/22,Boba Fett,183,78.2,black,fair,brown,31.5BBY,...,https://swapi.info/api/planets/10,Kamino,27.0,463.0,19720.0,temperate,1 standard,ocean,100,1000000000
21,23,IG-88,https://www.swapi.tech/api/people/23,IG-88,200,140,none,metal,red,15BBY,...,https://swapi.info/api/planets/28,unknown,0.0,0.0,0.0,unknown,unknown,unknown,unknown,unknown
22,24,Bossk,https://www.swapi.tech/api/people/24,Bossk,190,113,none,green,red,53BBY,...,https://swapi.info/api/planets/29,Trandosha,25.0,371.0,0.0,arid,0.62 standard,"mountains, seas, grasslands, deserts",unknown,42000000
23,25,Lando Calrissian,https://www.swapi.tech/api/people/25,Lando Calrissian,177,79,black,dark,brown,31BBY,...,https://swapi.info/api/planets/30,Socorro,20.0,326.0,0.0,arid,1 standard,"deserts, mountains",unknown,300000000
24,26,Lobot,https://www.swapi.tech/api/people/26,Lobot,175,79,none,light,blue,37BBY,...,https://swapi.info/api/planets/6,Bespin,12.0,5110.0,118000.0,temperate,"1.5 (surface), 1 standard (Cloud City)",gas giant,0,6000000
25,27,Ackbar,https://www.swapi.tech/api/people/27,Ackbar,180,83,none,brown mottle,orange,41BBY,...,https://swapi.info/api/planets/31,Mon Cala,21.0,398.0,11030.0,temperate,1,"oceans, reefs, islands",100,27000000000
26,28,Mon Mothma,https://www.swapi.tech/api/people/28,Mon Mothma,150,unknown,auburn,fair,blue,48BBY,...,https://swapi.info/api/planets/32,Chandrila,20.0,368.0,13500.0,temperate,1,"plains, forests",40,1200000000
27,29,Arvel Crynyd,https://www.swapi.tech/api/people/29,Arvel Crynyd,unknown,unknown,brown,fair,brown,unknown,...,https://swapi.info/api/planets/28,unknown,0.0,0.0,0.0,unknown,unknown,unknown,unknown,unknown
28,30,Wicket Systri Warrick,https://www.swapi.tech/api/people/30,Wicket Systri Warrick,88,20,brown,brown,brown,8BBY,...,https://swapi.info/api/planets/7,Endor,18.0,402.0,4900.0,temperate,0.85 standard,"forests, mountains, lakes",8,30000000

In [17]:
df = df.iloc[:, :3].join(df.iloc[:, 4:])

In [18]:
df

,uid,name,url,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,homeworld_name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population
0,1,Luke Skywalker,https://www.swapi.tech/api/people/1,172,77,blond,fair,blue,19BBY,male,https://swapi.info/api/planets/1,Tatooine,23.0,304.0,10465.0,arid,1 standard,desert,1,200000
1,2,C-3PO,https://www.swapi.tech/api/people/2,167,75,NaN,gold,yellow,112BBY,NaN,https://swapi.info/api/planets/1,Tatooine,23.0,304.0,10465.0,arid,1 standard,desert,1,200000
2,3,R2-D2,https://www.swapi.tech/api/people/3,96,32,NaN,white,blue,red,33BBY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Darth Vader,https://www.swapi.tech/api/people/4,202,136,none,white,yellow,41.9BBY,male,https://swapi.info/api/planets/1,Tatooine,23.0,304.0,10465.0,arid,1 standard,desert,1,200000
4,5,Leia Organa,https://www.swapi.tech/api/people/5,150,49,brown,light,brown,19BBY,female,https://swapi.info/api/planets/2,Alderaan,24.0,364.0,12500.0,temperate,1 standard,"grasslands, mountains",40,2000000000
5,6,Owen Lars,https://www.swapi.tech/api/people/6,178,120,brown,grey,light,blue,52BBY,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,Beru Whitesun lars,https://www.swapi.tech/api/people/7,165,75,brown,light,blue,47BBY,female,https://swapi.info/api/planets/1,Tatooine,23.0,304.0,10465.0,arid,1 standard,desert,1,200000
7,8,R5-D4,https://www.swapi.tech/api/people/8,97,32,NaN,white,red,red,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,Biggs Darklighter,https://www.swapi.tech/api/people/9,183,84,black,light,brown,24BBY,male,https://swapi.info/api/planets/1,Tatooine,23.0,304.0,10465.0,arid,1 standard,desert,1,200000
9,10,Obi-Wan Kenobi,https://www.swapi.tech/api/people/10,182,77,auburn,white,fair,blue-gray,57BBY,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,Anakin Skywalker,https://www.swapi.tech/api/people/11,188,84,blond,fair,blue,41.9BBY,male,https://swapi.info/api/planets/1,Tatooine,23.0,304.0,10465.0,arid,1 standard,desert,1,200000
11,12,Wilhuff Tarkin,https://www.swapi.tech/api/people/12,180,unknown,auburn,grey,fair,blue,64BBY,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,Chewbacca,https://www.swapi.tech/api/people/13,228,112,brown,unknown,blue,200BBY,male,https://swapi.info/api/planets/14,Kashyyyk,26.0,381.0,12765.0,tropical,1 standard,"jungle, forests, lakes, rivers",60,45000000
13,14,Han Solo,https://www.swapi.tech/api/people/14,180,80,brown,fair,brown,29BBY,male,https://swapi.info/api/planets/22,Corellia,25.0,329.0,11000.0,temperate,1 standard,"plains, urban, hills, forests",70,3000000000
14,15,Greedo,https://www.swapi.tech/api/people/15,173,74,NaN,green,black,44BBY,male,https://swapi.info/api/planets/23,Rodia,29.0,305.0,7549.0,hot,1 standard,"jungles, oceans, urban, swamps",60,1300000000
15,16,Jabba Desilijic Tiure,https://www.swapi.tech/api/people/16,175,1,358,NaN,green-tan,brown,orange,600BBY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,18,Wedge Antilles,https://www.swapi.tech/api/people/18,170,77,brown,fair,hazel,21BBY,male,https://swapi.info/api/planets/22,Corellia,25.0,329.0,11000.0,temperate,1 standard,"plains, urban, hills, forests",70,3000000000
17,19,Jek Tono Porkins,https://www.swapi.tech/api/people/19,180,110,brown,fair,blue,unknown,male,https://swapi.info/api/planets/26,Bestine IV,26.0,680.0,6400.0,temperate,unknown,"rocky islands, oceans",98,62000000
18,20,Yoda,https://www.swapi.tech/api/people/20,66,17,white,green,brown,896BBY,male,https://swapi.info/api/planets/28,unknown,0.0,0.0,0.0,unknown,unknown,unknown,unknown,unknown
19,21,Palpatine,https://www.swapi.tech/api/people/21,170,75,grey,pale,yellow,82BBY,male,https://swapi.info/api/planets/8,Naboo,26.0,312.0,12120.0,temperate,1 standard,"grassy hills, swamps, forests, mountains",12,4500000000
20,22,Boba Fett,https://www.swapi.tech/api/people/22,183,78.2,black,fair,brown,31.5BBY,male,https://swapi.info/api/planets/10,Kamino,27.0,463.0,19720.0,temperate,1 standard,ocean,100,1000000000
21,23,IG-88,https://www.swapi.tech/api/people/23,200,140,none,metal,red,15BBY,none,https://swapi.info/api/planets/28,unknown,0.0,0.0,0.0,unknown,unknown,unknown,unknown,unknown
22,24,Bossk,https://www.swapi.tech/api/people/24,190,113,none,green,red,53BBY,male,https://swapi.info/api/planets/29,Trandosha,25.0,371.0,0.0,arid,0.62 standard,"mountains, seas, grasslands, deserts",unknown,42000000
23,25,Lando Calrissian,https://www.swapi.tech/api/people/25,177,79,black,dark,brown,31BBY,male,https://swapi.info/api/planets/30,Socorro,20.0,326.0,0.0,arid,1 standard,"deserts, mountains",unknown,300000000
24,26,Lobot,https://www.swapi.tech/api/people/26,175,79,none,light,blue,37BBY,male,https://swapi.info/api/planets/6,Bespin,12.0,5110.0,118000.0,temperate,"1.5 (surface), 1 standard (Cloud City)",gas giant,0,6000000
25,27,Ackbar,https://www.swapi.tech/api/people/27,180,83,none,brown mottle,orange,41BBY,male,https://swapi.info/api/planets/31,Mon Cala,21.0,398.0,11030.0,temperate,1,"oceans, reefs, islands",100,27000000000
26,28,Mon Mothma,https://www.swapi.tech/api/people/28,150,unknown,auburn,fair,blue,48BBY,female,https://swapi.info/api/planets/32,Chandrila,20.0,368.0,13500.0,temperate,1,"plains, forests",40,1200000000
27,29,Arvel Crynyd,https://www.swapi.tech/api/people/29,unknown,unknown,brown,fair,brown,unknown,male,https://swapi.info/api/planets/28,unknown,0.0,0.0,0.0,unknown,unknown,unknown,unknown,unknown
28,30,Wicket Systri Warrick,https://www.swapi.tech/api/people/30,88,20,brown,brown,brown,8BBY,male,https://swapi.info/api/planets/7,Endor,18.0,402.0,4900.0,temperate,0.85 standard,"forests, mountains, lakes",8,30000000

In [ ]:
df.to_csv(".\data\swapi_all_merged.csv", index=False)